In [1]:
"""
STEP 2 of our ML project: Train a Linear Regression model.

WHAT this file does:
    1. Reads the house data we created.
    2. Splits it into a "training" part and a "testing" part.
    3. Teaches a Linear Regression model to predict price from the features.
    4. Checks how good the model is on data it has NEVER seen.
    5. Saves the trained model to a file so we can reuse it later.

WHY Linear Regression:
    It is the simplest useful ML model. It just draws the best straight-line
    relationship between the inputs (size, bedrooms, age) and the output (price).
    It literally tries to relearn the hidden rule we wrote in generate_data.py.
"""



'\nSTEP 2 of our ML project: Train a Linear Regression model.\n\nWHAT this file does:\n    1. Reads the house data we created.\n    2. Splits it into a "training" part and a "testing" part.\n    3. Teaches a Linear Regression model to predict price from the features.\n    4. Checks how good the model is on data it has NEVER seen.\n    5. Saves the trained model to a file so we can reuse it later.\n\nWHY Linear Regression:\n    It is the simplest useful ML model. It just draws the best straight-line\n    relationship between the inputs (size, bedrooms, age) and the output (price).\n    It literally tries to relearn the hidden rule we wrote in generate_data.py.\n'

In [1]:
import joblib               # used to save/load the trained model to a file
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

In [2]:


# --- 1. Load the data ---
data = pd.read_csv("house_data.csv")

# X = the inputs (what we know).  y = the answer we want to predict (price).
# Why separate them: the model needs to know which columns are questions
# and which column is the answer.
X = data[["size_sqft", "num_bedrooms", "age_years"]]
y = data["price"]

In [3]:


# --- 2. Split into training and testing sets ---
# WHY: If we test the model on the same data it learned from, it can "cheat"
# by memorising. We hold back 20% of houses so we can test on FRESH examples,
# which tells us how it will do on real, unseen houses.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [4]:
# --- 3. Train (a.k.a. "fit") the model ---
# .fit() is the actual learning step: it finds the best numbers (coefficients).
model = LinearRegression()
model.fit(X_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](3,)","[ 200.22,10895.93,-1488.87]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](3,)","['size_sqft','num_bedrooms','age_years']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,4.704e+04
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,3
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(3)


In [5]:
X_test.head()

,size_sqft,num_bedrooms,age_years
95,1364,3,16
15,2858,2,27
30,1851,3,3
158,2015,1,31
128,2223,1,36


In [6]:
y_test.head()

95     310025.0
15     596172.0
30     460544.0
158    432508.0
128    466938.0
Name: price, dtype: float64

In [7]:
# --- 4. Evaluate the model on the unseen test houses ---
predictions = model.predict(X_test)

mae = mean_absolute_error(y_test, predictions)   # average dollars we are "off" by
r2 = r2_score(y_test, predictions)               # 1.0 = perfect, 0.0 = useless

print("=== Model results ===")
print(f"Mean Absolute Error: ${mae:,.0f}  (average prediction miss)")
print(f"R^2 score:           {r2:.3f}       (closer to 1.0 is better)")


=== Model results ===
Mean Absolute Error: $11,494  (average prediction miss)
R^2 score:           0.993       (closer to 1.0 is better)


In [8]:
X.columns

Index(['size_sqft', 'num_bedrooms', 'age_years'], dtype='str')

In [ ]:
# Remember our hidden rule: +200 per sqft, +10000 per bedroom, -1500 per year.
model.coef_

array([  200.21837833, 10895.93466865, -1488.86785236])

In [11]:
# --- Show what the model LEARNED ---
# Remember our hidden rule: +200 per sqft, +10000 per bedroom, -1500 per year.
# The model should discover numbers close to these on its own!
print("\n=== What the model learned (compare to our hidden rule) ===")
for feature, coefficient in zip(X.columns, model.coef_):
    print(f"  {feature:15s}: {coefficient:>12,.1f}")
print(f"  {'base value':15s}: {model.intercept_:>12,.1f}")


=== What the model learned (compare to our hidden rule) ===
  size_sqft      :        200.2
  num_bedrooms   :     10,895.9
  age_years      :     -1,488.9
  base value     :     47,040.2


In [10]:
# --- 5. Save the trained model to a file ---
# WHY: training can be slow/expensive. We save the finished model so later steps
# (or a website, or Azure) can just LOAD it and make predictions instantly.
joblib.dump(model, "house_price_model.joblib")
print("\nSaved trained model to house_price_model.joblib")

# --- Bonus: use the model to predict a brand-new house ---
new_house = pd.DataFrame(
    {"size_sqft": [2000], "num_bedrooms": [3], "age_years": [10]}
)
predicted_price = model.predict(new_house)[0]
print(f"\nPredicted price for a 2000 sqft, 3-bed, 10-year-old house: ${predicted_price:,.0f}")



Saved trained model to house_price_model.joblib

Predicted price for a 2000 sqft, 3-bed, 10-year-old house: $465,276


In [11]:

import numpy as np
import pandas as pd

# A "seed" makes the random numbers come out the SAME every time we run this.
# Why: so your results match mine and are repeatable (important in real projects).
rng = np.random.default_rng(seed=42)

In [12]:
size_sqft = rng.integers(low=1, high=6, size=5) 

In [13]:
size_sqft

array([1, 4, 4, 3, 3])

In [14]:
n_houses = 5

# --- Invent the input features (the things we know about a house) ---
size_sqft = rng.integers(low=500, high=3500, size=n_houses)      # floor area
num_bedrooms = rng.integers(low=1, high=6, size=n_houses)        # 1 to 5 bedrooms
age_years = rng.integers(low=0, high=40, size=n_houses)          # how old the house is

# --- Invent the HIDDEN rule that decides the price ---
# price = base + (price per sqft) + (bonus per bedroom) - (penalty per year of age)
# We also add a little random "noise" so it looks like messy real-world data.
noise = rng.normal(loc=0, scale=15000, size=n_houses)

price = (
    50000                      # a base price every house starts with
    + 200 * size_sqft          # each square foot adds $200
    + 10000 * num_bedrooms     # each bedroom adds $10,000
    - 1500 * age_years         # each year of age removes $1,500
    + noise                    # random wobble
)


In [15]:
price

array([661690.96962294, 233066.87903143, 601890.46046342, 278208.61810452,
       226412.64013378])

## checking drift

In [16]:
import warnings

import pandas as pd
from evidently import Report
from evidently.presets import DataDriftPreset

In [13]:
warnings.filterwarnings("ignore", message="divide by zero encountered")

In [19]:
# --- 1. Load both datasets ---
# reference = the past (what the model was trained on)
# current   = the present (what the model is being asked about now)
reference_data = pd.read_csv("house_data.csv")
current_data = pd.read_csv("house_data_new.csv")

print(f"Reference (old) data: {len(reference_data)} rows")
print(f"Current   (new) data: {len(current_data)} rows")

Reference (old) data: 200 rows
Current   (new) data: 200 rows


In [20]:
report = Report([DataDriftPreset()])

In [21]:
result = report.run(reference_data=reference_data, current_data=current_data)

c:\Users\User\Documents\code_base\EY\azure_tutorial\house-price\.venv\Lib\site-packages\scipy\stats\_stats_py.py:7277: RuntimeWarning: divide by zero encountered in divide
  terms = (f_obs - f_exp)**2 / f_exp
c:\Users\User\Documents\code_base\EY\azure_tutorial\house-price\.venv\Lib\site-packages\scipy\stats\_stats_py.py:7277: RuntimeWarning:

divide by zero encountered in divide

c:\Users\User\Documents\code_base\EY\azure_tutorial\house-price\.venv\Lib\site-packages\scipy\stats\_stats_py.py:7277: RuntimeWarning:

divide by zero encountered in divide



In [22]:
# --- 3. Save the visual report ---
output_file = "drift_report.html"
result.save_html(output_file)
print(f"\nSaved report to {output_file} -- open it in your browser.")


Saved report to drift_report.html -- open it in your browser.


In [23]:
# --- 4. Also print a plain-text summary so you don't have to open the browser ---
# result.dict() turns the report into a normal Python dictionary of numbers.
summary = result.dict()

In [25]:
summary

{'metrics': [{'id': '15e89f895b482f9b84ba7274ed18a106',
   'metric_name': 'DriftedColumnsCount(drift_share=0.5)',
   'config': {'type': 'evidently:metric_v2:DriftedColumnsCount',
    'drift_share': 0.5},
   'value': {'count': 4.0, 'share': 1.0}},
  {'id': 'a51004a885b164180fb642348264b68d',
   'metric_name': 'ValueDrift(column=size_sqft,method=K-S p_value,threshold=0.05)',
   'config': {'type': 'evidently:metric_v2:ValueDrift',
    'column': 'size_sqft',
    'method': 'K-S p_value',
    'threshold': 0.05},
   'value': np.float64(6.753917316595921e-20)},
  {'id': '3acf044ff6c9f4748372a97e2c5994d8',
   'metric_name': 'ValueDrift(column=age_years,method=K-S p_value,threshold=0.05)',
   'config': {'type': 'evidently:metric_v2:ValueDrift',
    'column': 'age_years',
    'method': 'K-S p_value',
    'threshold': 0.05},
   'value': np.float64(1.3043607772628193e-43)},
  {'id': '0501170bea2d8c109692e8de32f4e6f9',
   'metric_name': 'ValueDrift(column=price,method=K-S p_value,threshold=0.05)',
 

In [26]:
print("\n=== Drift summary ===")
for metric in summary["metrics"]:
    # "config" holds what this metric was measuring, e.g. which column.
    config = metric["config"]
    kind = config["type"]          # e.g. "evidently:metric_v2:ValueDrift"
    value = metric["value"]

    # Metric 1: how many columns drifted in total.
    if kind.endswith("DriftedColumnsCount"):
        print(f"Columns that drifted: {value['count']:.0f} out of {len(reference_data.columns)}")
        print(f"That is {value['share']:.0%} of all columns.\n")

    # Metric 2..N: one verdict per column, where value IS the p-value.
    elif kind.endswith("ValueDrift"):
        column = config["column"]
        method = config["method"]  # K-S for numbers, chi-square for categories
        verdict = "DRIFT!" if value < 0.05 else "no drift"
        print(f"  {column:15s} p-value={value:<12.2e} ({method:22s}) -> {verdict}")

print(
    "\nHow to read this: p-value below 0.05 means the column really changed.\n"
    "(2.00e-20 is scientific notation for 0.00000...2 -- basically zero.)\n"
    "If important columns drifted, the honest next step is to RETRAIN the model\n"
    "on fresh data -- which is exactly what a scheduled Kedro job does in Part 4."
)



=== Drift summary ===
Columns that drifted: 4 out of 4
That is 100% of all columns.

  size_sqft       p-value=6.75e-20     (K-S p_value           ) -> DRIFT!
  age_years       p-value=1.30e-43     (K-S p_value           ) -> DRIFT!
  price           p-value=3.36e-63     (K-S p_value           ) -> DRIFT!
  num_bedrooms    p-value=0.00e+00     (chi-square p_value    ) -> DRIFT!

How to read this: p-value below 0.05 means the column really changed.
(2.00e-20 is scientific notation for 0.00000...2 -- basically zero.)
If important columns drifted, the honest next step is to RETRAIN the model
on fresh data -- which is exactly what a scheduled Kedro job does in Part 4.


In [ ]:
message = {
"start": "start",
  "end": "end"
}


status = message.get("status")   # "start" or "end"
status
